#!/bin/bash

usage()
{
  echo "tool-version - sets the tool to the specific version in your PATH"
  echo ""
  echo "Usage: tool-version [options]"
  echo ""
  echo "The options include:"
  echo "  -t, --tool          The tool to set the version for"
  echo "  -v, --version       The version of the tool"
  echo "  -b, --base-dir      The base directory for the tools (defaults to ~/apps)"
  echo "      --include-bin   Include \"/bin\" in the tool path"
  echo ""
  echo "Examples:"
  echo "  tool-version -t oc -v 4.18"
  echo "  tool-version -t java -v 21 --include-bin"
}

while [ "$1" != "" ]; do
  case $1 in
    --include-bin )     INCLUDE_BIN="true"
                        ;;
    -t | --tool )       shift
                        TOOL_NAME="$1"
                        ;;
    -v | --version )    shift
                        VERSION="$1"
                        ;;
    -b | --base-dir )   shift
                        BASE_DIR="$1"
                        ;;
    * )                 usage
                        exit 1
  esac
  shift
done

# check for missing parameters
if [[ -z $TOOL_NAME || -z $VERSION ]]; then
  echo "Missing parameters"
  usage
  exit 1
else
  # if the BASE_DIR wasn't set, use "$HOME/apps"
  if [[ -z "$BASE_DIR" ]]; then
    BASE_DIR="$HOME/apps"
  fi
fi
if [ ! -d "$BASE_DIR" ]; then
  echo "Base directory $BASE_DIR does not exist."
  exit 1
fi

TOOL_DIR="$BASE_DIR/$TOOL_NAME"
if [ ! -d "$TOOL_DIR" ]; then
  echo "Tool directory $TOOL_DIR does not exist."
  exit 1
fi

VERSION_DIR="$TOOL_DIR/$VERSION"
if [ ! -d "$VERSION_DIR" ]; then
  echo "Version directory $VERSION_DIR does not exist."
  exit 1
fi

# set the version
if [ -d "$TOOL_DIR/current" ]; then
  rm -rf "$TOOL_DIR/current"
fi
ln -s "$VERSION_DIR" "$TOOL_DIR/current"
echo "Set $TOOL_NAME to version $VERSION."
# Update the path
if ! grep -q "$TOOL_DIR/current" "$HOME/.path"; then
  if [[ "$INCLUDE_BIN" == "true" ]]; then
    echo "PATH=$TOOL_DIR/current/bin:\$PATH" >> "$HOME/.path"
  else
    echo "PATH=$TOOL_DIR/current:\$PATH" >> "$HOME/.path"
  fi
  echo "Updated PATH in .path."
else
  echo "PATH already updated in .path."
fi

# source the updated .path
echo "Run a 'source ~/.path' to update your PATH"
